# Generated by Django 5.1.2 on 2024-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
