# Generated by Django 5.1.2 on 2024-11-12 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCountriesStockPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_class', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=20)),
                ('security_name', models.CharField(max_length=100)),
                ('d_performance', models.FloatField(blank=True, null=True)),
                ('w_performance', models.FloatField(blank=True, null=True)),
                ('m_performance', models.FloatField(blank=True, null=True)),
                ('y_performance', models.FloatField(blank=True, null=True)),
                ('decade_performance', models.FloatField(blank=True, null=True)),
                ('index_most_recent_price', models.FloatField(blank=True, null=True)),
                ('fetch_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='fetch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
