# Generated by Django 5.1.2 on 2025-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('exchange_short_name', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('market_open_local', models.TimeField()),
                ('market_close_local', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('holiday_name', models.CharField(max_length=100)),
            ],
        ),
    ]
