# Generated by Django 5.1.2 on 2024-11-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_allcountriesstockperformance_dailyprice_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcountriesstockperformance',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
