# Generated by Django 5.1.2 on 2025-11-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_exchange_exchangeholiday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeHoliday',
            new_name='Exchange_Holiday',
        ),
    ]
