# Generated by Django 5.1.2 on 2024-11-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_dailyprice_high_dailyprice_low_dailyprice_open_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprice',
            old_name='close',
            new_name='adj_close',
        ),
    ]
