# Generated by Django 5.1.2 on 2025-11-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_rename_exchangeholiday_exchange_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
