# Generated by Django 5.1.2 on 2024-11-14 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_allcountriesstockperformance_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRegionsStockPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_class', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=20)),
                ('security_name', models.CharField(max_length=100)),
                ('d_performance', models.FloatField(blank=True, null=True)),
                ('w_performance', models.FloatField(blank=True, null=True)),
                ('m_performance', models.FloatField(blank=True, null=True)),
                ('y_performance', models.FloatField(blank=True, null=True)),
                ('decade_performance', models.FloatField(blank=True, null=True)),
                ('index_most_recent_price', models.FloatField(blank=True, null=True)),
                ('fetch_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
