# Generated by Django 5.1.2 on 2024-11-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_rename_close_dailyprice_adj_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='constituents_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='adj_close',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='AssetClass',
        ),
    ]
