# Generated by Django 5.1.2 on 2024-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_alter_asset_asset_class_asset_constituents_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='constituents_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
