# Generated by Django 5.1.2 on 2024-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_allregionsstockperformance_custom_region_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allregionsstockperformance',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
