# Generated by Django 5.1.2 on 2024-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_asset_constituents_count_alter_asset_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, default='unkown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, default='unkown', max_length=3, null=True),
        ),
    ]
