# Generated by Django 5.1.2 on 2024-11-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_asset_market_cap_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
