# Generated by Django 5.1.2 on 2024-11-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_alter_allregionsstockperformance_custom_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcountriesstockperformance',
            name='custom_region_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
