# Generated by Django 5.1.2 on 2024-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_dailyprice_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='adj_close',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='high',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='low',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='open',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
