# Generated by Django 5.1.2 on 2024-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_allcountriesstockperformance_custom_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allregionsstockperformance',
            name='country_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
