# Generated by Django 5.1.2 on 2025-11-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_historypage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sql_query', models.TextField(help_text='SQL query returning at least: date, value columns')),
                ('chart_type', models.CharField(choices=[('line', 'Line Chart'), ('area', 'Area Chart'), ('bar', 'Bar Chart')], default='line', max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('show_download', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='history.historypage')),
            ],
        ),
    ]
