# Generated by Django 5.1.2 on 2025-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_historychart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historychart',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('area', 'Area Chart'), ('bar', 'Bar Chart'), ('heatmap_mm', 'Money Market Heatmap')], default='line', max_length=30),
        ),
    ]
