# Generated by Django 5.1.2 on 2025-11-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_historychart_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historychart',
            name='periods_json',
            field=models.TextField(blank=True, help_text='JSON array of shading periods: [{"start": "YYYY-MM-DD", "end": "YYYY-MM-DD", "color": "rgba(...)"}]', null=True),
        ),
        migrations.AlterField(
            model_name='historychart',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('area', 'Area Chart'), ('bar', 'Bar Chart'), ('heatmap_mm', 'Money Market Heatmap'), ('line_with_periods', 'Line Chart With Shaded Periods')], default='line', max_length=30),
        ),
    ]
