# Generated by Django 5.1.2 on 2025-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_remove_historychart_periods_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historychart',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('area', 'Area Chart'), ('bar', 'Bar Chart'), ('heatmap_mm', 'Money Market Heatmap'), ('line_regime', 'Line with Regime Shading'), ('mad_hybrid', 'Money Market MAD')], default='line', max_length=30),
        ),
    ]
