# Generated by Django 5.1.2 on 2025-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_alter_historychart_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historychart',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line Chart'), ('area', 'Area Chart'), ('bar', 'Bar Chart'), ('line_regime', 'Line with Regime Shading'), ('heatmap_mm', 'Money Market Heatmap'), ('mad_hybrid', 'Money Market MAD'), ('mm_factor_map', 'Money Market Factor Map')], default='line', max_length=30),
        ),
    ]
