# Generated by Django 5.1.2 on 2025-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_alter_historychart_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historychart',
            name='chart_type',
            field=models.CharField(default='line', help_text="Chart type using dot-notation for hierarchical modules, e.g.: 'rates.policy_rates.mm_bubble_map'. Generic types also supported: 'line'.", max_length=200),
        ),
    ]
