# Generated by Django 5.1.2 on 2025-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_alter_historychart_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historychart',
            name='chart_type',
            field=models.CharField(choices=[('generic.line_generic', 'Generic Line Chart'), ('generic.line_regime', 'Line Chart with Regime Shading'), ('rates.policy_rates.mm_bubble_map', 'MM Bubble Map'), ('rates.policy_rates.mm_heatmap', 'MM Heatmap'), ('rates.policy_rates.mm_line_mad_hybrid', 'MM MAD Hybrid Line'), ('rates.policy_rates.mm_line_regime', 'MM Regime Line')], default='line', max_length=40),
        ),
    ]
